### ISSUE TITLE
How to properly distribute Firefox with WPP

### ISSUE THREAD

**Issue by romanvesely** [DCourtel/Wsus_Package_Publisher#51]
Hey,

every time I try to distribute the official Firefox MSI package with WPP, the installation runs into a loop and installs Firefox every hour or so on every machine I approved the update to. There is some german documentation on the web which says something about creating a certain rule when creating the Update, but I didn't have success yet with those... Could you maybe elaborate on this issue and what I should be doing to prevent Firefox from getting into that install loop?

I am distributing other packages like Java, Acrobat Reader, Chrome, PDF24 with WPP, which do not have these issue. Whats different with the Firefox MSI Package?

**Comment by StyleTec** [comment]
The firefox msi package does not write an entry in the registry, so that testing against the msi product code being installed is useless.

What you should do instead is, create an installed-rule having the "File Version" check included with path "Mozilla Firefox\firefox.exe" in well known directory "PROGRAM_FILES" and comparison "Greater Than Or Equal To" you installed version, so like 86.0.0.0 for the current version. For installable rules do the same rule, but choose "Less Than" for the comparison option. If you'd like to have the package also be used for new installations, change the AND-Group to OR-Group in installable rules and add a rule, that uses "File Exists" with the same path as the "File Version" rule and activate the "Reverse Rule" for it.

**Comment by romanvesely** [comment]
Thanks, I will try that. Did I get it right: If I want the package for new installations, do I keep the installable-rule with the "less than" property and add **another** rule with the "reverse rule" property or do I **replace** the installable rule with it?

Edit: also, my WPP crashes if I type in "Mozilla Firefox\firefox.exe" with quotation marks. Should I leave them? I wonder, because there is a space in the paths name

**Comment by StyleTec** [comment]
Add another rule and link them with the OR-Group

Just ignore quotes. They are only used by me for cosmetic reasons

**Comment by romanvesely** [comment]
Okay, thank you. It seems to work so far! I will be checking in a few days, see, if it will get into a loop again!
