### ISSUE TITLE
Issue with command syntax

### ISSUE THREAD

**Issue by Dalacor** [DCourtel/Wsus_Package_Publisher#89]
I have used WSUS Package Publisher for many years. So I am quite familiar with the program. However, I cannot get this particular software to work using WSUS Package Publisher.

https://outofthearksupport.zendesk.com/hc/en-gb/articles/9927815916945-Do-you-have-a-silent-install-version-of-the-Words-on-Screen-S-ngchronize-Player-

According to their instructions, I need to use this command:

/quiet WRAPPED_ARGUMENTS="/VERYSILENT" or /quiet WRAPPED_ARGUMENTS="/SILENT" 

I have tried the above with /, without /, with "" and without "". I have quiet, I have tried qn, I have tried q, I have tried /quiet, I have tried /qn and lastly /q. No matter what variables I try, nothing works. If I put in no variables, the program starts to install on a test machine, but then stops and waits for me to click, next, accept etc on the dialog boxes that come up. So the actual install works perfectly as it were. The problem is the program won't install silently as the syntax is obviously not working correctly.

Does anyone know exactly what syntax I should be using to get this to work with WSUS.

The error message I keep getting is Error 0x80070667

**Comment by Jetsord** [comment]
I faced sometimes the issue that a setup fails because of a other returncode (not 0). For .exe installations returncodes 1641 and 3010 are also "good".
Or for one installation the problem was that the setup fails because of "windows update installation is running" but the "windows update installation" is in this case the setup itselfs. 
So I write with WSUS PP a customized setup like. "1. stop wuauserv - 2. install setup.exe /quiet /etc - 3. start wuauserv"

**Comment by Dalacor** [comment]
I managed to solve the problem by running a silent install through group policy. Not ideal, but it was the only way to get the program installed. I think the fault lay more with the program than any issue with WSUS Package Publisher. Some software is just very badly written.
